Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,9 +1,66 @@
+# name: Build and Scan Docker Image with Trivy
+
+# on:
+#   push:
+#     branches:
+#       - main 
+#   workflow_dispatch:
+  
+# jobs:
+#   build_and_scan:
+#     runs-on: ubuntu-latest
+
+#     strategy:
+#   #    fail-fast: true
+#       matrix:
+#         language: ['python']
+
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v2
+
+#     - name: Set up Docker
+#       uses: docker/setup-buildx-action@v3
+
+#     - name: Build Docker Image
+#       run: |
+#         docker build -t trapp:v1 .
+   
+#     - name: Set up Trivy
+#       run: |
+#         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
+#       shell: bash
+
+#     - name: Scan Docker Image with Trivy
+#       run: |
+#         trivy image  --severity=HIGH trapp:v1
+#       #  --exit-code 1
+#       shell: bash
+      
+#     - name: Convert Trivy Results to SARIF
+#       run: |
+#         trivy image --severity=HIGH -f sarif trapp:v1 > trivy-results.sarif
+#       shell: bash
+
+#     # - name: Upload SARIF Results to Security Tab
+#     #   uses: github/codeql-action/upload-sarif@v2
+#     #   with:
+#     #     sarif_file: trivy-results.sarif
+#     - name: Upload SARIF Report
+#       uses: actions/upload-artifact@v2
+#       with:
+#         name: trivy-results
+#         path: trivy-results.sarif
+
+
 name: Build and Scan Docker Image with Trivy
 
 on:
   push:
-    branches:
-      - main 
+    # branches:
+    #   - main
+    #   - branch2
+  pull_request:
   workflow_dispatch:
   
 jobs:
@@ -34,7 +91,6 @@ jobs:
     - name: Scan Docker Image with Trivy
       run: |
         trivy image  --severity=HIGH trapp:v1
-      #  --exit-code 1
       shell: bash
       
     - name: Convert Trivy Results to SARIF
@@ -42,14 +98,19 @@ jobs:
         trivy image --severity=HIGH -f sarif trapp:v1 > trivy-results.sarif
       shell: bash
 
-    # - name: Upload SARIF Results to Security Tab
-    #   uses: github/codeql-action/upload-sarif@v2
-    #   with:
-    #     sarif_file: trivy-results.sarif
     - name: Upload SARIF Report
       uses: actions/upload-artifact@v2
       with:
         name: trivy-results
         path: trivy-results.sarif
-
+        
+    - name: Check vulnerability
+      run: |
+        trivy_output=$(trivy image --severity HIGH trapp:v1)
+        if echo "$trivy_output" | grep -q 'Total: 0'; then
+          echo 'No vulnerability found'
+        else
+          echo 'Vulnerability found'
+          exit 1
+        fi
 
